#!/bin/bash

#https://github.com/robbyrussell/oh-my-zsh
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    echo install oh-my-zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# https://github.com/zsh-users/zsh-autosuggestions
ZSH_CUSTOM=$HOME/.oh-my-zsh/custom # ???
if [[ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]]; then
    echo install zsh autosuggestion
    git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
fi

# https://github.com/tmux-plugins/tpm
if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
    echo install tmux plugin manager
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

dotfiles="$HOME/.dotfiles"

if [[ -d "$dotfiles" ]]; then
  echo "Symlinking dotfiles from $dotfiles"
else
  exit 1
fi

link() {
  from="$1"
  to="$2"
  echo "$from -> $to"
  rm -f "$to"
  ln -s "$from" "$to"
}

for location in $(find $dotfiles/home -type f); do
  file="${location#$dotfiles/home}"
  link "$location" "$HOME/$file"
done

if [ "$(uname)" == "Darwin" ]; then
    PHPSTORMDIR=$HOME/Library/Preferences/PhpStorm2016.3
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    PHPSTORMDIR=$HOME/.PhpStorm2016.3
fi

if [[ -n "$PHPSTORMDIR" && ! -d "$PHPSTORMDIR/colors" ]]; then
    ln -s $dotfiles/phpstorm/colors $PHPSTORMDIR/colors
fi
